### ISSUE TITLE
Unsoundness bug with smt2 file over real numbers.

### ISSUE THREAD

**Issue by KJongUk** [dreal/dreal4#255] opened 2021-07-02 08:27 UTC
With the following input, and precision=0.001 :
<pre>
<code>
(set-logic QF_NRA)
(declare-fun x () Real)
(assert (>= x 2.784764295834143))
(assert (< x 3.0))
(assert (= (^ x 1.9) 7))
(check-sat)
(exit)
</code>
</pre>
dReal(v.4.21.06.2) returns `unsat`. but I think this formula is `delta-sat`
(setup : Ubuntu 18.04)
So I'm wondering if there is something wrong.

**Comment by soonho-tri** [comment] 2021-07-02 10:34
1) The value of x should be close to `2.7847642958341389851065305282345246427561669476220511951193`, which is smaller than `2.784764295834143`. So the problem is `unsat`. Note that its delta-weakening can be `sat`.

2) When `φ` is `unsat` and `φᵟ` is `sat`, a delta-decision procedure is allowed to return one of the two answers. In this case, dReal returns `unsat`.

**Comment by KJongUk** [comment] 2021-07-04 06:35
Thanks for taking the time to answer this question, but I still have some question left.

when φ is `unsat` and φᵟ is `sat`, Is there some rules of a delta-decision procedure whether return value is `sat` or `unsat`?

**Comment by soonho-tri** [comment] 2021-07-04 11:45
> when φ is unsat and φᵟ is sat, Is there some rules of a delta-decision procedure whether return value is sat or unsat?

In theory, the problem is undecidable. An implication is that it's not possible to implement a delta-decision procedure which *always* returns an `unsat` answer for an `unsat` instance. On the other hand, it is acceptable for a delta-decision procedure to return `delta-sat` whenever a problem is `delta-sat`.

Practically, in my opinion, `unsat` answers should be preferred over `delta-dat` if a problem instance φ is `unsat`. We have implemented many heuristics to achieve this, but it is hard to enumerate the rules here.

**Comment by soonho-tri** [comment] 2021-07-04 11:47
I'm closing this issue here as it turns out this is not a bug.
If you want, we can continue this discussion without re-openning this issue.

**Closed by soonho-tri** 2021-07-04 11:47 UTC
Labels: question
