### ISSUE TITLE
Multivariable results in long computation time

### ISSUE THREAD

**Issue by LGM97** [dreal/dreal4#254] opened 2021-06-23 14:08 UTC
In my example, there are six variables, which leads to the calculation time of `CheckStatisfiability (condition, config)`  is too long to be applied. Config has been shrunk to 0.1. Are there any strategies to shorten the computing time?

**Comment by soonho-tri** [comment] 2021-06-23 14:09
Duplicate of #253.

**Closed by soonho-tri** 2021-06-23 14:09 UTC
