### ISSUE TITLE
Errors about dreal._dreal_py

### ISSUE THREAD

**Issue by leac123** [dreal/dreal4#166] opened 2019-12-28 17:24 UTC
from dreal._dreal_py import *

ImportError: libibex.so: cannot open shared object file: No such file or directory

How to fix this problem?

Many thanks!

**Comment by soonho-tri** [comment] 2019-12-28 17:29
Have you followed the instructions at https://pypi.org/project/dreal/ ?

> You still need to install dReal prerequisites such as IBEX and CLP in your system. To install them, please follow the instructions below:

**Comment by leac123** [comment] 2019-12-29 15:00
I tried to follow the instrucitons at the above link, but the following error appears:

Err:30 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
Fetched 616 kB in 3s (164 kB/s)
AppStream cache update completed, but some metadata was ignored due to errors.
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.opera.com/opera-stable stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B8EC3BAABDC4346
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/xenial/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Failed to fetch https://deb.opera.com/opera-stable/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B8EC3BAABDC4346
W: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/xenial/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden [IP: 91.189.95.83 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.


I cannot figure out where is the problem?

**Comment by soonho-tri** [comment] 2019-12-29 15:20
I think you can try this solution, https://askubuntu.com/a/943548.

**Comment by leac123** [comment] 2019-12-29 15:51
I have sucessfully install BEX and CLP in myu system, but the following erro still exists:

    from dreal._dreal_py import *
ImportError: libClpSolver.so.1: cannot open shared object file: No such file or directory

**Comment by soonho-tri** [comment] 2019-12-29 16:38
Thanks for the report. Actually, this is a duplicate of #165.

For now, a solution is to run the following. First of all, please uninstall dreal using pip3.

```bash
curl -fsSL https://raw.githubusercontent.com/dreal/dreal4/master/setup/ubuntu/`lsb_release -r -s`/install_prereqs.sh | sudo bash

pip3 install -e git+https://github.com/dreal/dreal4#egg=dreal
```

This is a temporary solution, I'll update the dReal python package later.

**Comment by leac123** [comment] 2019-12-29 16:41
Many thanks for your help but it still have problems. The error are as follows:

ERROR: An error occurred during the fetch of repository 'local_config_python':
       Traceback (most recent call last):
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 321
    		_create_local_python_repository(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 281, in _create_local_python_repository
    		_symlink_genrule_for_dir(<4 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in _symlink_genrule_for_dir
    		"\n".join(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in "\n".join
    		sorted(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in sorted
    		_read_dir(repository_ctx, <1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 82, in _read_dir
    		_execute(repository_ctx, <2 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 56, in _execute
    		_fail(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 27, in _fail
    		fail(<1 more arguments>)
    Python Configuration Error: Repository command failed
    find: ‘/usr/include/python3.6m’: No such file or directory
    
    INFO: Call stack for the definition of repository 'cds' which is a http_archive (rule definition at /home/lcong/.cache/bazel/_bazel_lcong/4816191c8df991c2e9527311408003fe/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/lcong/src/dreal/third_party/com_github_robotlocomotion_drake/tools/workspace/github.bzl:67:5
     - /home/lcong/src/dreal/dreal/workspace.bzl:87:5
     - /home/lcong/src/dreal/WORKSPACE:52:1
    INFO: Call stack for the definition of repository 'picosat' which is a http_archive (rule definition at /home/lcong/.cache/bazel/_bazel_lcong/4816191c8df991c2e9527311408003fe/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/lcong/src/dreal/third_party/com_github_robotlocomotion_drake/tools/workspace/github.bzl:67:5
     - /home/lcong/src/dreal/dreal/workspace.bzl:61:5
     - /home/lcong/src/dreal/WORKSPACE:52:1
    ERROR: /home/lcong/.cache/bazel/_bazel_lcong/4816191c8df991c2e9527311408003fe/external/pybind11/BUILD.bazel:3:1: @pybind11//:pybind11 depends on @local_config_python//:python_headers in repository @local_config_python which failed to fetch. no such package '@local_config_python//': Traceback (most recent call last):
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 321
    		_create_local_python_repository(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 281, in _create_local_python_repository
    		_symlink_genrule_for_dir(<4 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in _symlink_genrule_for_dir
    		"\n".join(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in "\n".join
    		sorted(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in sorted
    		_read_dir(repository_ctx, <1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 82, in _read_dir
    		_execute(repository_ctx, <2 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 56, in _execute
    		_fail(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 27, in _fail
    		fail(<1 more arguments>)
    Python Configuration Error: Repository command failed
    find: ‘/usr/include/python3.6m’: No such file or directory
    
    ERROR: Analysis of target '//dreal:_dreal_py.so' failed; build aborted: no such package '@local_config_python//': Traceback (most recent call last):
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 321
    		_create_local_python_repository(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 281, in _create_local_python_repository
    		_symlink_genrule_for_dir(<4 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in _symlink_genrule_for_dir
    		"\n".join(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in "\n".join
    		sorted(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 130, in sorted
    		_read_dir(repository_ctx, <1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 82, in _read_dir
    		_execute(repository_ctx, <2 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 56, in _execute
    		_fail(<1 more arguments>)
    	File "/home/lcong/src/dreal/third_party/com_github_tensorflow_tensorflow/py/python_configure.bzl", line 27, in _fail
    		fail(<1 more arguments>)
    Python Configuration Error: Repository command failed
    find: ‘/usr/include/python3.6m’: No such file or directory
    
    INFO: Elapsed time: 0.706s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    error: Unable to build dReal.
    Please visit https://pypi.org/project/dreal and follow the instructions to install the prerequsites.

**Comment by soonho-tri** [comment] 2019-12-29 16:46
I think it has something to do with how you install/use python-3.6 in your system (assuming that you are using it). Could you share how you do that?

**Comment by leac123** [comment] 2019-12-29 16:52
I use python 3.6.7 and the code is programmed on Pycharm. 
Thanks!

**Comment by soonho-tri** [comment] 2019-12-29 18:41
Just updated dReal package in pypi. Can you uninstall the old one and do `pip install dreal` again and test it?

**Comment by leac123** [comment] 2019-12-30 09:25
Many thanks for your help! It works now !

**Comment by soonho-tri** [comment] 2019-12-30 11:07
Great!

**Closed by soonho-tri** 2019-12-30 11:07 UTC
Labels: python
