### ISSUE TITLE
Expected UNSAT, got a model

### ISSUE THREAD

**Issue by AndreaCallia** [dreal/dreal4#171] opened 2020-02-25 20:40 UTC
Hi all,

With delta = 0.001 as accuracy, I would expect the following code to print `UNSAT` but it prints `SAT` and it returns a model which does not satisfy the only assertion provided.

Apparently, based on similar examples I tried, two things seem to affect this unexpected result:
1. having sums with more than two operands in assertions;
2. the fact that variables are unbounded or the fact that the range between their bounds is very big.

What do you think?

Attached code:
```c++
    #include <iostream>
    #include <string>
    
    #include <experimental/optional>
    #include <dreal/dreal.h>
    
    using namespace std;
    using namespace dreal;
    
    std::experimental::optional<dreal::Box> currentModel = {};
    
    int main(int argc, char* argv[]) {
        string t;
        Context s;
    
        Variable x1("x1", Variable::Type::CONTINUOUS);
        Variable x2("x2", Variable::Type::CONTINUOUS);
        Variable x3("x3", Variable::Type::CONTINUOUS);
        
        s.DeclareVariable(x1);
        s.DeclareVariable(x2);
        s.DeclareVariable(x3);
                
        s.Assert(x1 + x2 + x3 == 99);
        s.Assert(x1 + x2 + x3 == 90);
        
        currentModel = s.CheckSat();
        if (currentModel) cout << "SAT" << endl;
        else cout << "UNSAT" << endl;
        //if (currentModel) print_model();
        return 0;
    }
```

The model I get from the tool is also attached below:
```
    Model:
    x1 : [-6.652801031782400111e+291, -6.652801031782400111e+291]
    x2 : [-1.57298149300452602e+308, -1.57298149300452602e+308]
    x3 : [1.57298149300452602e+308, 1.57298149300452602e+308]
```

**Comment by scungao** [comment] 2020-02-25 20:47
When the x values are very large, under floating point semantics those
assertions can indeed both be “true”. The accuracy can’t be achieved in
those ranges (can’t prune to a smaller interval because the sparsity of
floating point representations), and we should print some warning.

**Comment by soonho-tri** [comment] 2020-07-25 22:24
Marked as a duplicate of #68.

**Closed by soonho-tri** 2020-07-25 22:24 UTC
Labels: bug
